name: Test Flask Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        activate-environment: ppk-env
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate ppk-env
        conda install -c conda-forge flask flask-login pandas numpy plotly
        pip install -r requirements.txt
        
    - name: Test application startup
      shell: bash -l {0}
      run: |
        conda activate ppk-env
        # 启动Flask应用作为后台进程
        python -c "from app import app; import threading; threading.Thread(target=lambda: app.run(debug=False)).start()" &
        
        # 等待应用启动
        sleep 2
        
        # 测试应用是否响应
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
        
        # 检查响应码是否为200或302（重定向到登录页）
        if [[ "$RESPONSE" == "200" || "$RESPONSE" == "302" ]]; then
          echo "应用程序启动成功，状态码: $RESPONSE"
          exit 0
        else
          echo "应用程序测试失败，状态码: $RESPONSE"
          exit 1
        fi